library(dplyr)
library(ggplot2)
library(grid)
library(gridExtra)
library(cowplot)
library(ggthemes)
library(reshape2)

integer_breaks <- function(n = 5, ...) {
  fxn <- function(x) {
    breaks <- floor(pretty(x, n, ...))
    names(breaks) <- attr(breaks, "labels")
    breaks
  }
  return(fxn)
}

#Read in the model projection summary statistics after considering parameter uncertainty (100 parameter sets from the posterior distribution of parameters) 
#Plotted as errorbars in the final figure
table_posterior<-read.csv("summmarytable_upplower_posterior_paraset_defounc_samehfpair.csv",header=TRUE)

#Read in the summary statistics over locations under each insect density, generated by the best parameter set 
#After considering stochasticity in parameters of the Weibull function in calculating defoliation percentage 
table<-read.csv("fullHiENDMfRel_hdefof_0.05_summarytable_defounc_samehfpair.csv",header=TRUE)
colnames(table)[4:5]<-c("5pct","95pct")
table$group<-as.character(table$group)
table$group[table$group=="Fraction_Infected"]<-"Fraction Infected"
table$group<-factor(table$group,levels=c("Fraction Infected","Defoliation"))
table$model<-factor(table$model,levels=c("normal","ndm","ndmh"))
table$insect_density<-table$insect_density*10000/250

color<-c("Fraction infected mean"="#a2cd5a","Fraction infected 5th/95th %iles"="#00563f","Defoliation mean"="#cc397b","Defoliation 5th/95th %iles"="#8b357f","Density frequencies"="grey50")
linetype_list<-c("Fraction infected mean"=1,"Fraction infected 5th/95th %iles"=1,"Defoliation mean"=2,"Defoliation 5th/95th %iles"=2)

table_base<-table[table$model=="normal",]
table_base$group<-factor(table_base$group,levels=c("Fraction Infected","Defoliation"))
table_base$title<-"Mean"

table_base<-melt(table_base, id.vars = c("insect_density", "pct_above0","group","model","title"))

#Matching the summary statistic by the best parameter set with the ones considering parameter uncertainty
table_base_comb<-left_join(table_base,table_posterior,by=c("insect_density","group","model","variable"))

table_base_comb$value[table_base_comb$group=="Fraction Infected"]<-table_base_comb$value[table_base_comb$group=="Fraction Infected"]*(-1)
table_base_comb$lower[table_base_comb$group=="Fraction Infected"]<-table_base_comb$lower[table_base_comb$group=="Fraction Infected"]*(-1)
table_base_comb$upper[table_base_comb$group=="Fraction Infected"]<-table_base_comb$upper[table_base_comb$group=="Fraction Infected"]*(-1)

table_base_comb$colorline[table_base_comb$group=="Fraction Infected"]<-"Fraction infected 5th/95th %iles"
table_base_comb$colorline[table_base_comb$group=="Fraction Infected" & table_base_comb$variable=="mean"]<-"Fraction infected mean"
table_base_comb$colorline[table_base_comb$group=="Defoliation"]<-"Defoliation 5th/95th %iles"
table_base_comb$colorline[table_base_comb$group=="Defoliation" & table_base_comb$variable=="mean"]<-"Defoliation mean"





#Read in the of 25th and 75th percentiles of model projections
table<-read.csv("fullHiENDMfRel_lowerupper_hdefof_0.05_summarytable_defounc_samehfpair.csv",header=TRUE)
colnames(table)[4:5]<-c("5pct","95pct")
table$group<-as.character(table$group)
table$group[table$group=="Fraction_Infected"]<-"Fraction Infected"
table$group<-factor(table$group,levels=c("Fraction Infected","Defoliation"))
table$model<-factor(table$model,levels=c("lower25","upper75"))
table$insect_density<-table$insect_density*10000/250

table_upper<-table[table$model=="upper75",]
table_upper$group<-factor(table_upper$group,levels=c("Fraction Infected","Defoliation"))
table_upper$title<-"Upper 75th"

table_upper<-melt(table_upper, id.vars = c("insect_density", "pct_above0","group","model","title"))

table_upper_comb<-left_join(table_upper,table_posterior,by=c("insect_density","group","model","variable"))

table_upper_comb$value[table_upper_comb$group=="Fraction Infected"]<-table_upper_comb$value[table_upper_comb$group=="Fraction Infected"]*(-1)
table_upper_comb$lower[table_upper_comb$group=="Fraction Infected"]<-table_upper_comb$lower[table_upper_comb$group=="Fraction Infected"]*(-1)
table_upper_comb$upper[table_upper_comb$group=="Fraction Infected"]<-table_upper_comb$upper[table_upper_comb$group=="Fraction Infected"]*(-1)

table_upper_comb$colorline[table_upper_comb$group=="Fraction Infected"]<-"Fraction infected 5th/95th %iles"
table_upper_comb$colorline[table_upper_comb$group=="Fraction Infected" & table_upper_comb$variable=="mean"]<-"Fraction infected mean"
table_upper_comb$colorline[table_upper_comb$group=="Defoliation"]<-"Defoliation 5th/95th %iles"
table_upper_comb$colorline[table_upper_comb$group=="Defoliation" & table_upper_comb$variable=="mean"]<-"Defoliation mean"


upper75<-ggplot(table_upper_comb)  + theme_clean()+
  geom_point(data=table_upper_comb[table_upper_comb$group=="Fraction Infected",],aes(x=insect_density,y=value,group=variable,color=colorline),size=3)+
  geom_line(data=table_upper_comb[table_upper_comb$group=="Fraction Infected",],aes(x=insect_density,y=value,group=variable,color=colorline,linetype=colorline),linewidth=1)+
  geom_errorbar(data=table_upper_comb[table_upper_comb$group=="Fraction Infected",],
                aes(x=insect_density,y=value,xmin=insect_density,xmax=insect_density,ymin=lower, ymax=upper,color=colorline), width=.2,
                position=position_identity())+
  scale_x_log10(breaks = scales::trans_breaks("log10", function(x) 10^x),labels = scales::trans_format("log10", scales::math_format(10^.x)),limits=c(6,100000))+
  scale_y_continuous(limits=c(-28,74),breaks=integer_breaks(),sec.axis = sec_axis(trans=~.*1.25,name="Increase in defoliation (%)",breaks=c(-25,0,25,50,75)))+
  geom_point(data=table_upper_comb[table_upper_comb$group=="Defoliation",],aes(x=insect_density,y=value/1.25,group=variable,color=colorline),size=3)+
  geom_line(data=table_upper_comb[table_upper_comb$group=="Defoliation",],aes(x=insect_density,y=value/1.25,group=variable,color=colorline,linetype=colorline),linewidth=1)+
  geom_errorbar(data=table_upper_comb[table_upper_comb$group=="Defoliation",],
                aes(x=insect_density,y=value/1.25,xmin=insect_density,xmax=insect_density,ymin=lower/1.25, ymax=upper/1.25,color=colorline), width=.2,
                position=position_identity())+
  xlab(expression(bold(paste("Initial insect density (egg masses/ha)")) ))+ylab(expression(bold("Relative decrease in infection (%)")))+
  theme(axis.line.y.right = element_line(color = "#cc397b"), 
        axis.ticks.y.right = element_line(color = "#cc397b"),
        axis.text.y.right = element_text(color = "#cc397b"), 
        axis.title.y.right = element_text(color = "#cc397b"))+
  theme(plot.title=element_text(size=28,face="bold"), axis.text=element_text(size=24),
        axis.title=element_text(size=24,face="bold"),plot.background = element_blank(),
        legend.position = c(0.2,0.79),legend.title=element_blank(),legend.text=element_text(size=24),legend.background=element_blank(),legend.key=element_blank(),
        strip.background =element_rect(fill="grey50"),strip.text = element_text(colour = 'white'), legend.key.width = unit(3,"cm"))+
  theme(axis.title.y.right = element_text(margin = margin(t = 0, r = 0, b = 0, l = 10)))+
  scale_color_manual(breaks=c("Fraction infected mean","Fraction infected 5th/95th %iles","Defoliation mean","Defoliation 5th/95th %iles","Density frequencies"),values=color,name="value type")+
  scale_fill_manual(breaks=c("Fraction infected mean","Fraction infected 5th/95th %iles","Defoliation mean","Defoliation 5th/95th %iles","Density frequencies"),values=color,name="value type")+ 
  scale_linetype_manual(breaks=c("Fraction infected mean","Fraction infected 5th/95th %iles","Defoliation mean","Defoliation 5th/95th %iles"),values=linetype_list,name="value type")+
  #ggtitle(expression(bold(paste("G_i<=0.05"))))+theme(plot.title = element_text(hjust = 0.5))+
  facet_grid(. ~ title)+theme(strip.text.x = element_text(size=28,face="bold"))+theme(panel.spacing.x = unit(2, "lines"))
#scale_x_continuous(trans=log_trans(),breaks=round(exp(-5:-1),3),limits=c(0.004,0.38))+
#facet_wrap(~group)+theme(strip.text.x = element_text(size=24,face="bold"),strip.text.y = element_text(size=24,face="bold"))+theme(panel.spacing.x = unit(2, "lines"))




table_lower<-table[table$model=="lower25",]
table_lower$group<-factor(table_lower$group,levels=c("Fraction Infected","Defoliation"))
table_lower$title<-"Lower 25th"

table_lower<-melt(table_lower, id.vars = c("insect_density", "pct_above0","group","model","title"))

table_lower_comb<-left_join(table_lower,table_posterior,by=c("insect_density","group","model","variable"))

table_lower_comb$value[table_lower_comb$group=="Fraction Infected"]<-table_lower_comb$value[table_lower_comb$group=="Fraction Infected"]*(-1)
table_lower_comb$lower[table_lower_comb$group=="Fraction Infected"]<-table_lower_comb$lower[table_lower_comb$group=="Fraction Infected"]*(-1)
table_lower_comb$upper[table_lower_comb$group=="Fraction Infected"]<-table_lower_comb$upper[table_lower_comb$group=="Fraction Infected"]*(-1)

table_lower_comb$colorline[table_lower_comb$group=="Fraction Infected"]<-"Fraction infected 5th/95th %iles"
table_lower_comb$colorline[table_lower_comb$group=="Fraction Infected" & table_lower_comb$variable=="mean"]<-"Fraction infected mean"
table_lower_comb$colorline[table_lower_comb$group=="Defoliation"]<-"Defoliation 5th/95th %iles"
table_lower_comb$colorline[table_lower_comb$group=="Defoliation" & table_lower_comb$variable=="mean"]<-"Defoliation mean"




table_total<-rbind(table_base_comb,table_upper_comb,table_lower_comb)
table_total$title<-factor(table_total$title,levels=c("Upper 75th","Mean","Lower 25th"))

plot_facet<-ggplot(table_total,aes(x=insect_density,y=value,group=variable,color=colorline))  + theme_clean()+
  geom_point(size=3)+
  geom_line(linewidth=1)+
  geom_errorbar(aes(xmin=insect_density,xmax=insect_density,ymin=lower, ymax=upper,color=colorline), width=.2,
                position=position_identity(),size=1)+
  scale_x_log10(breaks = scales::trans_breaks("log10", function(x) 10^x),labels = scales::trans_format("log10", scales::math_format(10^.x)),limits=c(6,100000))+
  scale_y_continuous(breaks=integer_breaks())+
  xlab(expression(bold(paste("Initial insect density (egg masses/ha)")) ))+ylab(expression(bold("Change in infection / defoliation (%)")))+
  theme(axis.line.y.right = element_line(color = "#cc397b"), 
        axis.ticks.y.right = element_line(color = "#cc397b"),
        axis.text.y.right = element_text(color = "#cc397b"), 
        axis.title.y.right = element_text(color = "#cc397b"))+
  theme(plot.title=element_text(size=32,face="bold"), axis.text=element_text(size=28),
        axis.title=element_text(size=28,face="bold"),plot.background = element_blank(),
        legend.position = c(0.5,0.66),legend.title=element_blank(),legend.text=element_text(size=20),legend.background=element_blank(),legend.key=element_blank(),
        strip.background =element_rect(fill="grey50"),strip.text = element_text(colour = 'white'), legend.key.width = unit(2,"cm"))+
  theme(axis.title.y.right = element_text(margin = margin(t = 0, r = 0, b = 0, l = 10)))+
  scale_color_manual(breaks=c("Fraction infected mean","Fraction infected 5th/95th %iles","Defoliation mean","Defoliation 5th/95th %iles","Density frequencies"),values=color,name="value type")+
  scale_fill_manual(breaks=c("Fraction infected mean","Fraction infected 5th/95th %iles","Defoliation mean","Defoliation 5th/95th %iles","Density frequencies"),values=color,name="value type")+ 
  scale_linetype_manual(breaks=c("Fraction infected mean","Fraction infected 5th/95th %iles","Defoliation mean","Defoliation 5th/95th %iles"),values=linetype_list,name="value type")+
  #ggtitle(expression(bold(paste("G_i<=0.05"))))+theme(plot.title = element_text(hjust = 0.5))+
  facet_grid(title ~ group)+theme(strip.text.x = element_text(size=28,face="bold"),strip.text.y = element_text(size=28,face="bold"))+theme(panel.spacing.x = unit(2, "lines"),panel.spacing.y = unit(2, "lines"))
#scale_x_continuous(trans=log_trans(),breaks=round(exp(-5:-1),3),limits=c(0.004,0.38))+
#facet_wrap(~group)+theme(strip.text.x = element_text(size=24,face="bold"),strip.text.y = element_text(size=24,face="bold"))+theme(panel.spacing.x = unit(2, "lines"))


jpeg(paste("EX_Figure1_summary_stochasticity.jpg",sep=""),height=3000,width=4000,res=300)
grid.arrange(plot_facet,nrow=1)
#grid.arrange(g_IT)

dev.off()   